name: CV3dgs
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.7.13
  - plyfile=0.8.1
  - pyntcloud
  - pip=22.3.1
  - pytorch=1.12.1
  - torchaudio=0.12.1
  - torchvision=0.13.1
  - cudatoolkit=11.6
  - pillow
  - tqdm
  - scikit-learn
  - matplotlib
  - pip:
      - open3d